### ISSUE TITLE
better combat animations showing sword double

### ISSUE THREAD

**Issue by NotTheRealRoKur0** [xTracr/RealCamera#59]
I see my first person player model doing the attack animation + the better combat hand animation.
theres no way to disable the better combat item from rendering.
[using realcamera-0.6.0-alpha.2]

video showcasing the problem:
https://drive.google.com/file/d/1ADCL5M0I7HRXqOz0qWtbShYdrg1hsyz8/view?usp=sharing

**Comment by xTracr** [comment]
In fact, 0.6.0-beta hasn't been released in these days is because this issue  
If this is solved, shadows are not rendered when using shaders
![1 20 1-fabric_2024-03-08 18-25-17](https://github.com/xTracr/RealCamera/assets/57320980/2fec4165-9c1a-4fca-8b17-b373510ad5cf)
I read the source code of Better Combat and Iris then, and I think it would be better for the author of Better Combat to handle the issue  
just need to do the same as for compatibility with First Person Model

**Comment by xTracr** [comment]
I have just fixed it by simply modifying the value of a field in the code of Better Combat  
[snapshot](https://github.com/xTracr/RealCamera/actions/runs/8203828912)

**Comment by Turker9002** [comment]
a little confused, how do i fix it :(

**Comment by RavensVanity** [comment]
> I see my first person player model doing the attack animation + the better combat hand animation. theres no way to disable the better combat item from rendering. [using realcamera-0.6.0-alpha.2]
> 
> video showcasing the problem: https://drive.google.com/file/d/1ADCL5M0I7HRXqOz0qWtbShYdrg1hsyz8/view?usp=sharing


Hey, I was hoping you could tell me how you fixed this. Thanks in advance :) Hope to hear from you soon
